name: Render Quarto Document

on:
  push:
    branches:
      - main   # Run on pushes to the main branch

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up R environment
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.3" # Specify R version
        

            
    # Step 3: Install Quarto CLI
    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: "latest" # Or specify a version like "1.3.433"

    # Step 4: Install R dependencies
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
            any::tidyverse 
            any::tidyCDISC
            any::networkD3
            any::plotly
            any::ggalluvial
            any::knitr

    # Step 5: Render Quarto script
    - name: Render Quarto Document
      run: |
        quarto render sankey.qmd --to html
        ls -l # List files to confirm output

